version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: tburtin
      POSTGRES_PASSWORD: toto
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"